default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_manager_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: book_manager_test
  url: <%= ENV.fetch("DATABASE_URL_TEST", nil) %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
